server:
  port: ${PORT:8090}
  servlet:
    context-path: v1
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

