server:
  port: ${PORT:8090}
  servlet:
    encoding:
      charset: UTF-8
#    context-path: /v1
spring:
  application:
    name: app-forum
  profiles:
    active: ${PROFILE:dev}
  security:
    filter:
      order: 10

jwt:
  secret: super_secreta

