server:
  port: ${PORT:8090}
  servlet:
    encoding:
      charset: UTF-8
    context-path: /v1
spring:
  application:
    name: app-forum
  profiles:
    active: ${PROFILE:dev}

jwt:
  secret: super_secreta