CREATE TABLE TB_ROLE(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    NOME VARCHAR(50) NOT NULL
);

INSERT INTO TB_ROLE(NOME)
VALUES
    ( 'ROLE_ADMIN' ),
    ('ROLE_GERENTE'),
    ('ROLE_OPERADOR'),
    ('ROLE_CLIENT');