CREATE TABLE TB_USUARIO_ROLE(
    ID_USUARIO BIGINT NOT NULL,
    ID_ROLE BIGINT NOT NULL ,
    FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID),
    FOREIGN KEY(ID_ROLE) REFERENCES TB_ROLE(ID)
);

INSERT INTO TB_USUARIO_ROLE(ID_USUARIO, ID_ROLE)
VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (2, 2),
    (2, 4),
    (3, 4),
    (4, 4),
    (4, 3),
    (5, 4);